-- ============================================================================
-- Migration 047 — DIPENSIUNKAN. Berkas ini sengaja TIDAK melakukan apa pun.
-- ============================================================================
--
-- Ratifikasi founder 2026-08-03 (R-001, opsi A). Isi lama berkas ini dapat
-- dibaca di git history: `git show 263387c:db/migrations/047_general_ledger.sql`.
--
-- ── Apa yang dulu ada di sini
--
-- 047 membuat General Ledger versi pertama: `accounts`, `journal_entries`,
-- `journal_entry_lines` — semuanya **single-tenant**. Kolom jenis akun bernama
-- `account_type`, dan **tidak ada `company_id` sama sekali** (nol kemunculan).
--
-- ── Kenapa dipensiunkan, dan kenapa ini P0
--
-- Migrasi **167** membangun ulang GL dalam bentuk **tenant-aware**: `company_id`
-- NOT NULL di ketiga tabel, kolom jenis akun bernama `type`, penomoran jurnal
-- per-company. Keduanya memakai `CREATE TABLE IF NOT EXISTS`.
--
-- `IF NOT EXISTS` melindungi dari "tabel sudah dibuat oleh migrasi INI" —
-- **bukan** dari "tabel sudah dibuat oleh migrasi LAIN dengan bentuk berbeda".
-- Maka di lingkungan mana pun yang menjalankan migrasi berurutan dari nol
-- (CI hari ini, produksi nanti):
--
--   1. 047 jalan lebih dulu → `accounts` terbentuk TANPA `company_id`.
--      SQL-nya sah, jadi tidak error, jadi tidak masuk `SKIP_ALLOWLIST`
--      di `ci-project-setup.mjs`, jadi tidak memicu HARD FAIL.
--   2. 167 menyusul → melihat tabelnya sudah ada → **no-op senyap**.
--   3. Hasil akhir: **buku besar tidak bisa memisahkan perusahaan.**
--
-- Tak ada pesan galat. Tak ada test merah. Baru ketahuan ketika perusahaan
-- kedua membuka jurnal dan melihat angka perusahaan pertama — yaitu setelah
-- kerusakannya permanen.
--
-- ── Kenapa AMAN memensiunkannya (bukan sekadar nyaman)
--
-- Diverifikasi 2026-08-02/03 lewat `scripts/db/ledger-diff.mjs`:
--
--   · Di **dev**: 047 tercatat di buku migrasi, tetapi SELURUH artefaknya
--     TIDAK ADA (9 objek: fungsi `set_accounts_updated_at`,
--     `protect_journal_entries_created_at`, dan 7 index). `accounts` yang hidup
--     di dev adalah bentuk **167** — terbukti punya `company_id` dan kolom `type`.
--     Artinya 047 memang tak pernah benar-benar dijalankan di dev.
--   · Di **project CI**: diperiksa terpisah oleh
--     `apps/api/scripts/ci-periksa-bentuk-gl.mjs` (R-001 syarat 1). Bila di sana
--     `accounts` terbentuk dari 047 (tanpa `company_id`), project CI WAJIB
--     di-reset dari nol — tabel itu tak bisa diperbaiki dengan menjalankan 167,
--     persis karena `IF NOT EXISTS`.
--   · **Nol data produksi.** `journal_entries` berisi 0 baris. Ini jendela
--     termurah yang akan pernah ada untuk memperbaikinya.
--
-- ── Kenapa berkas ini tidak dihapus saja
--
-- Nomor 047 SUDAH TERCATAT di `supabase_migrations.schema_migrations`. Menghapus
-- berkasnya membuat buku menunjuk ke sesuatu yang tak ada, dan
-- `audit-penomoran-migrasi.mjs` akan melaporkannya sebagai lompatan baru.
-- Menomori ulangnya jauh lebih berbahaya lagi. Yang benar: berkasnya tetap ada,
-- isinya dikosongkan, alasannya ditulis di tempat orang berikutnya akan mencari.
--
-- ── Preseden
--
-- Pola ini bukan hal baru di repo ini. Migrasi **149** menghadapi persoalan yang
-- sama persis terhadap forward-draft **045** (`assets` tanpa `company_id`), dan
-- menyelesaikannya dengan membuang bentuk lama lebih dulu — lihat komentar
-- panjang di `149_asset_register.sql` baris 50-73. Selisihnya: 149 masih perlu
-- mendefinisikan tabelnya, sedangkan di sini 167 sudah melakukannya, sehingga
-- 047 cukup menjadi no-op.
--
-- ── Penegas bentuk
--
-- Perlindungan agar cacat ini tak bisa kembali TIDAK diletakkan di berkas ini,
-- melainkan di **175_gl_penegas_bentuk.sql** — yang berjalan SETELAH 167 dan
-- GAGAL KERAS bila `accounts` ternyata tanpa `company_id`. Penjaga statiknya:
-- `apps/api/scripts/audit-tabrakan-definisi-tabel.mjs` (dijalankan CI).
-- ============================================================================

-- Sengaja tanpa operasi. Jangan menambahkan DDL di sini — GL didefinisikan
-- sepenuhnya oleh migrasi 167 dan seterusnya.
DO $$
BEGIN
  RAISE NOTICE '047: dipensiunkan (R-001, 2026-08-03) — GL didefinisikan oleh migrasi 167. Tidak ada operasi.';
END $$;
